version: '3.9'

services:
  java_app:
    container_name: java_app
    image: product-java-app:1.0.0
    build: .
    ports:
      - 8001:8001 # Puerto de la aplicación Java (host:container)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/PRODUCTOS
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1818
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432  # Puerto de la base de datos PostgreSQL (host:container)
    environment:
      - POSTGRES_DB=PRODUCTOS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1818

