FROM openjdk:22

# Copiar el archivo JAR de la construcción del proyecto al contenedor
COPY target/product-service-0.0.1-SNAPSHOT.jar java-app.jar

# Definir el punto de entrada
ENTRYPOINT ["java", "-jar", "java-app.jar"]
